-- =====================================================================
-- Consent Management Schema for WSO2 Identity Server
-- Database: identity_db
-- Purpose: Add missing consent management tables required for OAuth DCR
-- =====================================================================
-- 
-- These tables are required for WSO2 IS 7.1+ to properly manage OAuth
-- applications created via Dynamic Client Registration (DCR).
-- 
-- Without these tables, you'll get:
--   org.postgresql.util.PSQLException: ERROR: relation "cm_receipt" does not exist
-- 
-- Apply this script after the main identity_db schema (04-identity-db-schema.sql)
-- =====================================================================

-- Table: CM_RECEIPT
-- Stores consent receipts for user data usage
CREATE TABLE IF NOT EXISTS CM_RECEIPT (
  CONSENT_RECEIPT_ID VARCHAR(255) NOT NULL,
  VERSION VARCHAR(255),
  JURISDICTION VARCHAR(255),
  CONSENT_TIMESTAMP TIMESTAMP NOT NULL,
  COLLECTION_METHOD VARCHAR(255),
  LANGUAGE VARCHAR(255),
  PII_PRINCIPAL_ID VARCHAR(255),
  PRINCIPAL_TENANT_ID INTEGER DEFAULT -1234,
  POLICY_URL VARCHAR(255),
  STATE VARCHAR(255),
  PII_CONTROLLER VARCHAR(2048),
  PRIMARY KEY (CONSENT_RECEIPT_ID)
);

-- Table: CM_RECEIPT_SP_ASSOC
-- Associates consent receipts with service providers (OAuth applications)
CREATE TABLE IF NOT EXISTS CM_RECEIPT_SP_ASSOC (
  ID SERIAL,
  CONSENT_RECEIPT_ID VARCHAR(255) NOT NULL,
  SP_NAME VARCHAR(255),
  SP_DISPLAY_NAME VARCHAR(255),
  SP_DESCRIPTION VARCHAR(1023),
  SP_TENANT_ID INTEGER DEFAULT -1234,
  PRIMARY KEY (ID),
  CONSTRAINT CM_RECEIPT_SP_ASSOC_CNT UNIQUE (CONSENT_RECEIPT_ID, SP_NAME, SP_TENANT_ID),
  FOREIGN KEY (CONSENT_RECEIPT_ID) REFERENCES CM_RECEIPT (CONSENT_RECEIPT_ID) ON DELETE CASCADE
);

-- Table: CM_SP_PURPOSE_ASSOC
-- Associates service providers with data usage purposes
CREATE TABLE IF NOT EXISTS CM_SP_PURPOSE_ASSOC (
  ID SERIAL,
  RECEIPT_SP_ASSOC INTEGER,
  PURPOSE_ID INTEGER NOT NULL,
  CONSENT_TYPE VARCHAR(255),
  IS_PRIMARY_PURPOSE CHAR(1) DEFAULT '0',
  TERMINATION VARCHAR(255),
  THIRD_PARTY_DISCLOSURE CHAR(1) DEFAULT '0',
  THIRD_PARTY_NAME VARCHAR(255),
  PRIMARY KEY (ID),
  CONSTRAINT CM_SP_PURPOSE_ASSOC_fk0 FOREIGN KEY (RECEIPT_SP_ASSOC) REFERENCES CM_RECEIPT_SP_ASSOC (ID) ON DELETE CASCADE
);

-- Table: CM_PURPOSE
-- Defines purposes for data collection and usage
CREATE TABLE IF NOT EXISTS CM_PURPOSE (
  ID SERIAL,
  NAME VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(1023),
  PURPOSE_CATEGORY VARCHAR(255),
  GROUP_TYPE VARCHAR(255),
  TENANT_ID INTEGER DEFAULT -1234,
  PRIMARY KEY (ID),
  UNIQUE (NAME, TENANT_ID, GROUP_TYPE)
);

-- Table: CM_PII_CATEGORY
-- Categories of Personally Identifiable Information (PII)
CREATE TABLE IF NOT EXISTS CM_PII_CATEGORY (
  ID SERIAL,
  NAME VARCHAR(255) NOT NULL,
  DISPLAY_NAME VARCHAR(255),
  IS_SENSITIVE INTEGER DEFAULT 0,
  TENANT_ID INTEGER DEFAULT -1234,
  PRIMARY KEY (ID),
  UNIQUE (NAME, TENANT_ID)
);

-- Table: CM_PURPOSE_PII_CAT_ASSOC
-- Associates purposes with PII categories
CREATE TABLE IF NOT EXISTS CM_PURPOSE_PII_CAT_ASSOC (
  ID SERIAL,
  PURPOSE_ID INTEGER NOT NULL,
  CM_PII_CATEGORY INTEGER NOT NULL,
  IS_MANDATORY INTEGER DEFAULT 0,
  PRIMARY KEY (ID),
  FOREIGN KEY (PURPOSE_ID) REFERENCES CM_PURPOSE (ID) ON DELETE CASCADE,
  FOREIGN KEY (CM_PII_CATEGORY) REFERENCES CM_PII_CATEGORY (ID) ON DELETE CASCADE
);

-- Table: CM_SP_PURPOSE_PII_CAT_ASSOC
-- Associates service provider purposes with PII categories
CREATE TABLE IF NOT EXISTS CM_SP_PURPOSE_PII_CAT_ASSOC (
  ID SERIAL,
  SP_PURPOSE_ASSOC_ID INTEGER NOT NULL,
  PII_CATEGORY_ID INTEGER NOT NULL,
  VALIDITY VARCHAR(1023),
  PRIMARY KEY (ID),
  FOREIGN KEY (SP_PURPOSE_ASSOC_ID) REFERENCES CM_SP_PURPOSE_ASSOC (ID) ON DELETE CASCADE
);

-- Table: CM_CONSENT_RECEIPT_PROPERTY
-- Stores additional properties for consent receipts
CREATE TABLE IF NOT EXISTS CM_CONSENT_RECEIPT_PROPERTY (
  ID SERIAL,
  CONSENT_RECEIPT_ID VARCHAR(255) NOT NULL,
  NAME VARCHAR(255),
  VALUE VARCHAR(2047),
  PRIMARY KEY (ID),
  FOREIGN KEY (CONSENT_RECEIPT_ID) REFERENCES CM_RECEIPT (CONSENT_RECEIPT_ID) ON DELETE CASCADE
);

-- Table: CM_PURPOSE_CATEGORY
-- Categories of data usage purposes
CREATE TABLE IF NOT EXISTS CM_PURPOSE_CATEGORY (
  ID SERIAL,
  NAME VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(1023),
  TENANT_ID INTEGER DEFAULT -1234,
  PRIMARY KEY (ID),
  UNIQUE (NAME, TENANT_ID)
);

-- Table: CM_SP_PURPOSE_PURPOSE_CAT_ASSC
-- Associates service provider purposes with purpose categories
CREATE TABLE IF NOT EXISTS CM_SP_PURPOSE_PURPOSE_CAT_ASSC (
  ID SERIAL,
  SP_PURPOSE_ASSOC_ID INTEGER NOT NULL,
  PURPOSE_CATEGORY_ID INTEGER NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (SP_PURPOSE_ASSOC_ID) REFERENCES CM_SP_PURPOSE_ASSOC (ID) ON DELETE CASCADE,
  FOREIGN KEY (PURPOSE_CATEGORY_ID) REFERENCES CM_PURPOSE_CATEGORY (ID) ON DELETE CASCADE
);

-- =====================================================================
-- Schema installation complete
-- Total tables created: 10
-- =====================================================================
