[server]
hostname = "localhost"
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[user_store]
type = "database_unique_id"

[database.identity_db]
type = "postgre"
url = "jdbc:postgresql://postgres:5432/identity_db"
username = "wso2carbon"
password = "wso2carbon"
driver = "org.postgresql.Driver"
validationQuery = "SELECT 1"

[database.shared_db]
type = "postgre"
url = "jdbc:postgresql://postgres:5432/shared_db_is"
username = "wso2carbon"
password = "wso2carbon"
driver = "org.postgresql.Driver"
validationQuery = "SELECT 1"

[keystore.primary]
file_name = "wso2carbon.p12"
password = "wso2carbon"
type="PKCS12"

[truststore]
file_name="client-truststore.p12"
password="wso2carbon"
type="PKCS12"

[account_recovery.endpoint.auth]
hash= "66cd9688a2ae068244ea01e70f0e230f5623b7fa4cdecb65070a09ec06452262"

[identity.auth_framework.endpoint]
app_password= "dashboard"

# The KeyStore which is used for encrypting/decrypting internal data. By default the primary keystore is used as the internal keystore.

#[keystore.internal]
#file_name = "$ref{keystore.primary.file_name}"
#type = "$ref{keystore.primary.type}"
#password = "$ref{keystore.primary.password}"
#alias = "$ref{keystore.primary.alias}"
#key_password = "$ref{keystore.primary.key_password}"

# The KeyStore which is used for tls communication. By default the primary keystore is used as the tls keystore.

#[keystore.tls]
#file_name = "$ref{keystore.primary.file_name}"
#type = "$ref{keystore.primary.type}"
#password = "$ref{keystore.primary.password}"
#alias = "$ref{keystore.primary.alias}"
#key_password = "$ref{keystore.primary.key_password}"

#Google reCAPTCHA settings.

#[recaptcha]
#enabled = true
#api_url = "https://www.google.com/recaptcha/api.js"
#verify_url = "https://www.google.com/recaptcha/api/siteverify"
#site_key = ""
#secret_key = ""

# SMTP email sender settings.
#[output_adapter.email]
#from_address= "abcd@gmail.com"
#username= "abcd"
#password= "xxxx"
#hostname= "smtp.gmail.com"
#port= 587

# PostgreSQL connection pool settings
[database.identity_db.pool_options]
maxActive = 100
maxWait = 60000
minIdle = 5
testOnBorrow = true
validationInterval = 30000
defaultAutoCommit = false

[database.shared_db.pool_options]
maxActive = 100
maxWait = 60000
minIdle = 5
testOnBorrow = true
validationInterval = 30000
defaultAutoCommit = false

# Enable DCR (Dynamic Client Registration) endpoint
# Required for OAuth application registration via API
[[resource.access_control]]
context = "(.*)/api/identity/oauth2/dcr(.*)"
secure = true
http_method = "all"
permissions = ["/permission/admin/manage/identity/applicationmgt"]
scopes = []
